version: "3.7"
services:
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
    - 27017:27017
    env_file:
      .env

  flask:
    image: plytix_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    depends_on:
      - mongodb
    env_file:
      .env